In [1]:
import pandas as pd

url = "/content/drive/MyDrive/DATASET/orders.csv"

df = pd.read_csv(url, index_col="order_id")

df.head()
df.tail()

         customer_name   product  quantity  unit_price  order_date     status
order_id
1016       Paul Harris     Mouse       6.0       499.0  2024-01-30    pending
1017      Quinn Martin   Monitor       NaN     14500.0  2024-01-31  delivered
1018       Rachel King    Laptop       1.0     85000.0         NaN  delivered
1019        Sam Wright  Keyboard       3.0      1200.0  2024-02-01  cancelled
1020        Tina Baker   USB Hub       2.0       799.0  2024-02-02    pending

In [2]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1001 to 1020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_name  20 non-null     object
 1   product        20 non-null     object
 2   quantity       16 non-null     float64
 3   unit_price     20 non-null     float64
 4   order_date     16 non-null     object
 5   status         20 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.1+ KB

customer_name    0
product          0
quantity         4
unit_price       0
order_date       4
status           0
dtype: int64

In [3]:
pd.to_datetime(df["order_date"])

order_id
1001   2024-01-15
1002   2024-01-16
1003          NaT
1004   2024-01-18
1005   2024-01-19
1006   2024-01-20
1007   2024-01-21
1008          NaT
1009   2024-01-23
1010   2024-01-24
1011   2024-01-25
1012   2024-01-26
1013          NaT
1014   2024-01-28
1015   2024-01-29
1016   2024-01-30
1017   2024-01-31
1018          NaT
1019   2024-02-01
1020   2024-02-02
Name: order_date, dtype: datetime64[ns]

In [4]:
df.describe()

        quantity    unit_price
count  16.000000     20.000000
mean    2.437500  20224.600000
std     1.504161  33573.389607
min     1.000000    499.000000
25%     1.000000    799.000000
50%     2.000000   2500.000000
75%     3.000000  14625.000000
max     6.000000  85000.000000

In [5]:
df["unit_price"].median()

2500.0